var panel2 = { 
	template: `
  <section class="p-5">
    <div class="container">

      <p>
        <strong>
          <a href="index.html#/panel">Panel-1</a> / Panel-2
        </strong>
      </p>

      <p class="conf-title" name="title">Panel-2: </p>
      <p class="conf-title">Intelligence computing for emergent human-machine ecosystem</p>

      <p class="main-p mt-4">
        <strong>Introduction to the topic:</strong>
        The prevalence and penetration of billions of sensors, devices and
        embedded systems, namely the Internet of Things (IoT), and the rapid
        development of IoT, AI and data science enabled smart
        cyber-physical-social systems, have heralded a new era where human and
        machines are interwoven into an ecosystem across real and virtual world.
        The growing computation power enabled by cloud and edge computing,
        coupled with the ever-increasing machine learning and statistical
        methods, boosted by the availability of big data generated by the
        Internet of Things (IoT), mobile devices and social networks, have
        already led to a great leap in the capabilities and huge potentials of
        computational machine intelligence, as evidenced by recent
        ground-breaking AI development like AlphaGo and ChatGPT. While humans
        want machines to be intelligent, thus serving them, as much as possible,
        and yet they concern that these machines with full autonomy may one day
        outperform them to become too powerful to be controlled. The blend of
        desire and fear has led to a number of emerging research areas under the
        general banner of human machine intelligence computing, including
        user-centred smart cyber-physical systems, human-in-the-loop AI versus
        machine-in-the-loop AI, hybrid human-artificial intelligence (also being
        referred to as hybrid intelligence or hyper intelligence) and
        cyber-physical-social computing, as well as responsible or trustworthy
        AI, to name but a few. This is an area of probably evolving on a daily
        basis, and yet an area of extreme importance on a number of frontiers,
        not only the development of technologies and applications but also the
        EDI, transparency and accountability, thus worth keeping under close
        check constantly.
      </p>

      <p class="main-p">
        This Panel is intended to provide a forum for internationally
        recognised, world-class researchers to share their visions, views and
        insights into the concepts, approaches, open questions and challenges in
        the research and development of human machine computing. It is expected
        that the Panel presentation and discussions will stimulate new thinking,
        shape future research directions and foster research collaborations, and
        ultimately advance the scientific frontier and ensure responsible,
        sustainable and innovative AI applications.
      </p>

      <div class="row">
        <div class="col-2">
          <img class="img-fluid crop" src="./assets/commitee/limingchen.jpg" alt="" />
        </div>

        <div class="col-8">
          <p class="conf-mtitle">Chair: Liming Chen</p>
          <p class="main-p">Ulster University, UK</p>
          <p class="main-p">Date: Oct 22, 2023</p>
        </div>
      </div>

      <p class="main-p mt-2">
        <strong>Panelist:</strong>
        Laurance Tianruo Yang, Hui Xiong, Chau Yuen, Xing Xie, Bin Guo
      </p>

      <p class="conf-subtitle">Panelist</p>

      <p class="conf-mtitle">Laurance Tianruo Yang</p>

      <p class="main-p">
        Laurence Tianruo Yang (Fellow, IEEE) received the B.E. degree in
        computer science and technology and the B.Sc. degree in applied physics
        from Tsinghua University, Beijing, China, in 1992, and the Ph.D. degree
        in computer science from the University of Victoria, Victoria, BC,
        Canada, in 2006. He is currently a Professor and vice president at
        Hainan University, China; His research has been supported by the
        National Sciences and Engineering Research Council, Canada, and the
        Canada Foundation for Innovation. His current research interests include
        parallel and distributed computing, embedded and ubiquitous/pervasive
        computing, and big data.
      </p>

      <p class="conf-mtitle">Hui Xiong</p>

      <p class="main-p">
        Dr. Hui Xiong received his Ph.D. in Computer Science from the University
        of Minnesota - Twin Cities, USA, in 2005, the B.E. degree in Automation
        from the University of Science and Technology of China (USTC), Hefei,
        China, and the M.S. degree in Computer Science from the National
        University of Singapore (NUS), Singapore. He is currently a
        Distinguished Professor at Rutgers, the State University of New Jersey,
        where he received the 2018 Ram Charan Management Practice Award as the
        Grand Prix winner from the Harvard Business Review, RBS Dean's Research
        Professorship (2016), two-year early promotion/tenure (2009), the
        Rutgers University Board of Trustees Research Fellowship for Scholarly
        Excellence (2009), the ICDM-2011 Best Research Paper Award (2011), the
        Junior Faculty Teaching Excellence Award (2007), Dean's Award for
        Meritorious Research (2010, 2011, 2013, 2015) at Rutgers Business
        School, the 2017 IEEE ICDM Outstanding Service Award (2017), and the
        AAAI-2021 Best Paper Award (2021). Dr. Xiong is also a Distinguished
        Guest Professor (Grand Master Chair Professor) at the University of
        Science and Technology of China (USTC). For his outstanding
        contributions to data mining and mobile computing, he was elected an ACM
        Distinguished Scientist in 2014, an IEEE Fellow and an AAAS Fellow in
        2020.
      </p>

      <p class="conf-mtitle">Chau Yuen</p>

      <p class="main-p">
        Chau Yuen (S02-M06-SM12-F21) received the B.Eng. and Ph.D. degrees from
        Nanyang Technological University, Singapore, in 2000 and 2004,
        respectively. He was a Post-Doctoral Fellow with Lucent Technologies
        Bell Labs, Murray Hill, in 2005, and a Visiting Assistant Professor with
        The Hong Kong Polytechnic University in 2008. From 2006 to 2010, he was
        with the Institute for Infocomm Research, Singapore. From 2010 to 2023,
        he was with the Engineering Product Development Pillar, Singapore
        University of Technology and Design. Since 2023, he has been with the
        School of Electrical and Electronic Engineering, Nanyang Technological
        University. Dr. Yuen received IEEE Communications Society Fred W.
        Ellersick Prize (2023), IEEE Marconi Prize Paper Award in Wireless
        Communications (2021), and EURASIP Best Paper Award for JOURNAL ON
        WIRELESS COMMUNICATIONS AND NETWORKING (2021). He was a recipient of the
        Lee Kuan Yew Gold Medal, the Institution of Electrical Engineers Book
        Prize, the Institute of Engineering of Singapore Gold Medal, the Merck
        Sharp and Dohme Gold Medal, and twice a recipient of the Hewlett Packard
        Prize. He received the IEEE Asia Pacific Outstanding Young Researcher
        Award in 2012 and IEEE VTS Singapore Chapter Outstanding Service Award
        on 2019. He is a Distinguished Lecturer of IEEE Vehicular Technology
        Society, Top 2% Scientists by Stanford University, and also a Highly
        Cited Researcher by Clarivate Web of Science. He has 3 US patents and
        published over 500 research papers at international journals or
        conferences.
      </p>

      <p class="conf-mtitle">Xing Xie</p>

      <p class="main-p">
        Dr. Xing Xie is currently a senior principal research manager of
        Microsoft Research Asia, and a guest Ph.D. advisor at the University of
        Science and Technology of China. He received his B.S. and Ph.D. degrees
        in Computer Science from the University of Science and Technology of
        China in 1996 and 2001, respectively. He joined Microsoft Research Asia
        in July 2001, working on data mining, social computing and responsible
        AI. During the past years, he has published over 300 papers, won the
        IEEE MDM 2023 test-of-time award, the ACM SIGKDD 2022 test-of-time
        award, the ACM SIGKDD China 2021 test of time award, the 10-year impact
        award honorable mention in ACM SIGSPATIAL 2020(opens in new tab), the
        10-year impact award in ACM SIGSPATIAL 2019(opens in new tab), the best
        student paper award in KDD 2016(opens in new tab), and the best paper
        awards in ICDM 2013 and UIC 2010. He has been invited to give keynote
        speeches at ChineseCSCW 2022(opens in new tab), CCDM 2022(opens in new
        tab), CCIR 2020(opens in new tab), MDM 2019(opens in new tab), HHME
        2018(opens in new tab), ASONAM 2017(opens in new tab), MobiQuitous
        2016(opens in new tab), SocInfo 2015, W2GIS 2011, etc. He currently
        serves on the editorial boards of ACM Transactions on Recommender
        Systems (ToRS)(opens in new tab), ACM Transactions on Social Computing
        (TSC)(opens in new tab), ACM Transactions on Intelligent Systems and
        Technology (TIST)(opens in new tab), CCF Transactions on Pervasive
        Computing and Interaction (CCF TPCI)(opens in new tab). He served as
        program co-chair of ACM Ubicomp 2011(opens in new tab), the 8th Chinese
        Pervasive Computing Conference (PCC 2012), the 12th IEEE International
        Conference on Ubiquitous Intelligence and Computing (UIC 2015(opens in
        new tab)), the 6th National Conference on Social Media Processing (SMP
        2017), ACM SIGSPATIAL 2021(opens in new tab), ACM SIGSPATIAL 2022(opens
        in new tab), IEEE MDM 2022(opens in new tab), and will be a program
        co-chair of PAKDD 2024 and IEEE BigData 2025. In Oct. 2009, he founded
        the SIGSPATIAL China chapter which was the first regional chapter of ACM
        SIGSPATIAL. He is a Fellow of China Computer Federation (CCF) and the
        IEEE, and a Distinguished Member of ACM.
      </p>

      <p class="conf-mtitle">Bin Guo</p>

      <p class="main-p">
        Dr. Bin Guo is currently a professor of Northwestern Polytechnical
        University, China. He was previous a post-doctoral researcher of Prof.
        Daqing Zhang's research group at Institute TELECOM SudParis, France. He
        received his Ph.D. degree in computer science from Keio University,
        Tokyo, Japan, in 2009. He completed his Ph.D studies in the Anzai-Imai
        Lab, under the supervision of Prof. Michita Imai and Prof. Yuichiro
        Anzai (president of JSPS in Japan). He received his B.E and M.E of
        Computer Science from Xi'an Jiaotong University in 2003 and 2006,
        respectively. He serves as the vice-dean of the School of Computer
        Science, the deputy director of the Intelligent Sensing and Computing
        Lab. of the Ministry of Industry and Information Technology of China,
        the founding director of the AI&Art Research Center of NPU，and the
        Secretary General of the Belt and Road AIoT International Cooperative
        Alliance (BRAVE).
      </p>
    </div>
  </section>
  `
}