var callForAIIOTSpecialTrack = { 
	template: `
  <section class="p-5">
    <div class="container">
      <p class="conf-title">Artificial intelligence for the Industrial Internet of Things (AIIoT)</p>

      <p class="conf-subtitle">1.Introduction:</p>

      <p class="main-p">
        Artificial intelligence (AI) is a key component in the Industrial 
        Internet of Things (IIoT) ecosystem, which is a network of physical 
        devices, machines, and software applications that communicate and 
        exchange data in order to optimize industrial processes. With the 
        help of AI, IIoT systems can extract valuable insights from large 
        volumes of data generated by sensors, machines, and other connected 
        devices, and use that information to optimize processes, improve 
        efficiency, and reduce costs. AI technologies such as machine 
        learning, computer vision, and natural language processing are being 
        used to enable predictive maintenance, quality control, supply 
        chain management, and other industrial applications. As the IIoT 
        continues to evolve, AI is expected to play an increasingly important 
        role in driving innovation and transforming the way in which 
        businesses operate.
      </p>

      <p class="main-p">
      This Special Track aims to collect original and high-quality 
      submissions related to AI in Industrial Internet of Things. 
      The topics relevant to this special issue include but are not 
      limited to:
      </p>

      <p class="main-p">
        <ul>
          <li>Systems for IoT and services computing</li>
          <li>Industrial IoT in manufacturing</li>
          <li>AI technologies in industrial IoT</li>
          <li>Security and privacy in industrial IoT</li>
          <li>Wearable devices</li>
          <li>Cyber-physical systems</li>
          <li>Software engineering for industrial IoT</li>
          <li>Machine learning and deep learning approaches for data analysis</li>
          <li>Social implications for IoT intelligent</li>
          <li>Resilient and secure IoT with real-world solutions</li>
        </ul>
      </p>

      <p class="conf-subtitle">2.Submission information:</p>

      <p class="main-p">
        <strong>Please follow the same submission guideline as for the general tracks.</strong>
      </p>

      <p class="conf-subtitle">3.Guested editors:</p>
      <p class="main-p">
        Helei Cui (Northwestern Polytechnical University)
      </p>

      <p class="main-p">
        Xing Huang (Northwestern Polytechnical University)
      </p>

      <p class="main-p">
        Xiaoning (Maggie) Liu (RMIT University)
      </p>

    </div>
  </section>
  `
};